chmod 755 /etc/sysctl.d/
chmod 644 /etc/sysctl.conf
chmod 640 /etc/passwd
chmod 640 /etc/shadow
chmod 640 /etc/group
chmod 640 /etc/gshadow
chmod 755 /etc/sudoers.d/
chmod 440 /etc/sudoers
chmod 644 /etc/login.defs
chmod 644 /etc/rc.local
chmod 700 /etc/grub.d/
chmod 644 /etc/securetty
chmod 644 /etc/security/limits.conf
chmod 644 /etc/fstab
chmod 644 /etc/environment
chmod 600 /boot/grub2/grub.cfg
chmod 755 /etc
chmod 555 /usr/bin
chmod 555 /boot
chmod 755 /dev
chmod 755 /home
chmod 755 /lib
chmod 755 /media
chmod 755 /mnt
chmod 755 /opt
chmod 555 /proc/
chmod 750 /root
chmod 755 /run
chmod 555 /usr/sbin
chmod 755 /srv
chmod 555 /sys
chmod 1777 /tmp
chmod 755 /usr
chmod 755 /var/
chmod 640 /var/log/btmp
chmod 640 /var/log/wtmp
chmod 640 /var/log/lastlog
chown root:root /etc/sysctl.d/
chown root:root /etc/sysctl.conf
chown root:root /etc/passwd
chown root:root /etc/shadow
chown root:root /etc/group
chown root:root /etc/gshadow
chown root:root /etc/sudoers.d/
chown root:root /etc/sudoers.d/*
chown root:root /etc/sudoers
chown root:root /etc/login.defs
chown root:root /etc/pam.d/system-auth
chown root:root /etc/pam.d/password-auth
chown root:root /etc/rc.local
chown root:root /etc/grub.d/
chown root:root /etc/securetty
chown root:root /etc/security/limits.conf
chown root:root /etc/fstab
chown root:root /etc/updatedb.conf
chown root:root /etc/modprobe.d/blacklist.conf
chown root:root /etc/environment
chown root:root /boot/grub2/grub.cfg
chown root:root /etc
chown root:root /bin
chown root:root /boot
chown root:root /dev
chown root:root /home
chown root:root /lib
chown root:root /media
chown root:root /mnt
chown root:root /opt
chown root:root /proc/
chown root:root /root
chown root:root /run
chown root:root /sbin
chown root:root /srv
chown root:root /sys
chown root:root /tmp
chown root:root /usr
chown root:root /var/
